insert into siswa (nama, umur) values ('Lotstring', 36);
insert into siswa (nama, umur) values ('Latlux', 21);
insert into siswa (nama, umur) values ('Latlux', 37);
insert into siswa (nama, umur) values ('Latlux', 34);
insert into siswa (nama, umur) values ('Mat Lam Tam', 27);
insert into siswa (nama, umur) values ('Lotlux', 27);
insert into siswa (nama, umur) values ('Redhold', 39);
insert into siswa (nama, umur) values ('Matsoft', 22);
insert into siswa (nama, umur) values ('Voyatouch', 27);
insert into siswa (nama, umur) values ('Alpha', 47);
insert into siswa (nama, umur) values ('Asoka', 28);
insert into siswa (nama, umur) values ('Mat Lam Tam', 36);
insert into siswa (nama, umur) values ('Tempsoft', 37);
insert into siswa (nama, umur) values ('Zaam-Dox', 28);
insert into siswa (nama, umur) values ('Keylex', 25);
insert into siswa (nama, umur) values ('Trippledex', 40);
insert into siswa (nama, umur) values ('Tresom', 43);
insert into siswa (nama, umur) values ('Sonair', 35);
insert into siswa (nama, umur) values ('Bigtax', 44);
insert into siswa (nama, umur) values ('Holdlamis', 30);
